name: Hola mundo
on: push

jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: |
        echo $MI_VARIABLE.
  Mi-segundo-job:
    needs: Mi-primer-job
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      run: |
        echo el primer job dijo: $MI_VARIABLE.

